name: Deploy to S3 And Invalidate Cloudfront

on:
  push:
    branches:
      - feature/minhyuk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Checkout
        uses: actions/checkout@v4

      - name: Install node packages
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Debuggin build Project
        run: |
          ls
          cd dist
          ls
